Base project
thefuntasty/FuntastyKit pull request #1
Opened 2016-12-19 12:38 UTC by zvonicek

- Support for CocoaPods, Carthage, SwiftPM
- iOS, MacOS, tvOS, watchOS targets
- Coordinator, SessionHolder, Nibable, Keyboardable, HairlineLayoutConstraint, UIView Extensions, proper UITableView/UICollectionView deselection handling

2016-12-19 15:51 UTC, mkj-is requested changes
The most important thing is to review all the methods, protocols and objects if they are correctly accessible from outside modules.

2016-12-19 15:51 UTC, mkj-is commented on FuntastyKit.podspec
> +  s.summary      = " A collection of Swift utilities and protocols used in our projects."
Space at the beginning of description?

2016-12-19 15:51 UTC, mkj-is commented on FuntastyKit.podspec
> +  s.social_media_url   = ""
Funtasty Twitter?

2016-12-19 15:51 UTC, mkj-is commented on Sources/Architecture/Coordinator.swift
> +        viewController?.dismiss(animated: true, completion: {
What about?

`viewController?.dismiss(animated: true) {`

2016-12-19 15:51 UTC, mkj-is commented on Sources/Architecture/Coordinator.swift
> +        if let _ = destinationNavigationController {
I propose `!= nil`

2016-12-19 15:51 UTC, mkj-is commented on Sources/Architecture/Coordinator.swift
> +            viewController?.dismiss(animated: true, completion: {
Completion block?

2016-12-19 15:51 UTC, mkj-is commented on Sources/Extensions/UIWindow+RootViewController.swift
> +            }, completion: { (finished) -> Void in
Maybe improve the completion and send the bool from the function paramater.

2016-12-19 15:51 UTC, mkj-is commented on Sources/Extensions/UIWindow+RootViewController.swift
> +            UIView.transition(with: self, duration: 0.3, options: .transitionCrossDissolve, animations: { () -> Void in
Maybe add the durartion to function paramater with default value.

2016-12-19 15:51 UTC, mkj-is commented on Sources/FuntastyKit.swift
> + *  FuntastyKit
👍

2016-12-19 15:54 UTC, zvonicek commented on Sources/Extensions/UIWindow+RootViewController.swift
> +            }, completion: { (finished) -> Void in
+ pass nil value there if needed

2016-12-19 16:06 UTC, hrach commented on FuntastyKit.podspec
>    s.name         = "FuntastyKit"
the random indentation of `=` is not very nice :-)

2016-12-19 16:12 UTC, zvonicek commented on FuntastyKit.podspec
>    s.name         = "FuntastyKit"
I don't like it either, this file was actually pre-generated ;-)

2016-12-20 08:45 UTC, mkj-is approved these changes

2016-12-20 09:28 UTC, merged