Add stopUsingKeyboard to Keyboardable protocol
thefuntasty/FuntastyKit pull request #13
Opened 2017-03-05 20:57 UTC by crinos9

`stopUsingKeyboard` has to be called before dismissing screen otherwise observers will remain active.

It also fixes problem deinit of object that uses this protocol. It was caused by registering observer with function instead of a block with `[weak self]`.

2017-03-05 22:26 UTC, zvonicek commented
Thanks for the PR 👍  `stopUsingKeyboard` is really a needed addition. Change of the notification handlers from functions to closures is an interesting idea which I'm OK with, but I'm adding Keyboardable author @mkj-is as a reviewer to say his stand on this ;-)

2017-03-05 22:33 UTC, zvonicek reviewed
Please mind the missing public accessors

2017-03-05 22:33 UTC, zvonicek commented on Sources/Protocols/Keyboardable.swift
> +protocol Keyboardable: class {
Please put back the public accessors, otherwise the Keyboardable will not be available throughout CocoaPods framework

2017-03-05 22:33 UTC, zvonicek commented on Sources/Protocols/Keyboardable.swift
> +extension Keyboardable { //where Self: UIViewController {
Again the case with public accessors. As for the commented out `where`, I think it's not that important to have it there so you can remove it.

2017-03-06 12:31 UTC, mkj-is requested changes
Nice, thank you. I am still thinking whether this can be done better without the requirement of implementing the `keyboardObservers` property. Still, it does not look like it. :(

2017-03-06 12:31 UTC, mkj-is commented on Sources/Protocols/Keyboardable.swift
> +    var keyboardObserver: [Any] { get set }
`keyboardObservers`?

2017-03-19 19:45 UTC, crinos9 commented on Sources/Protocols/Keyboardable.swift
> +    var keyboardObserver: [Any] { get set }
https://github.com/thefuntasty/FuntastyKit/pull/13/commits/0cae9161b48ca6304df40029b66022844c5ed150

2017-03-22 08:27 UTC, mkj-is approved these changes

2017-03-22 08:30 UTC, zvonicek approved these changes

2017-03-22 08:30 UTC, merged